### ISSUE TITLE
System.TypeException : Apex Class does not have a no-arg constructor

### ISSUE THREAD

**Issue by rarpit** [mitchspano/apex-trigger-actions-framework#99] opened 2023-01-06 16:40 UTC
## Expected Behavior
Framework should query records without throwing exception.

## Actual Behavior
System.TypeException : <Query Class> does not have a no-arg constructor

## Steps to Reproduce the Problem
Followed documentation for https://github.com/mitchspano/apex-trigger-actions-framework#avoid-repeated-queries
1. Create an Apex class to query SOQL records (TA_Opportunity_Queries)
2. Open Execute Anonymous Window
3. Execute - Object triggerInstance = Type.forName('TA_Opportunity_Queries').newInstance();
Above statement is equivalent to MetadataTriggerHandler (line 192).
4. System.TypeException: TA_Opportunity_Queries does not have a no-arg constructor. 

## Specifications

- Version: current
- Platform: salesforce

**Comment by mitchspano** [comment] 2023-01-06 17:07
Hello @rarpit - thank you for checking out the framework and raising this issue.

In the documentation, you can see that we author an inner class called `Service` which is the Trigger Action, and the top level class is the [Singleton](https://refactoring.guru/design-patterns/singleton).

```java
public class TA_Opportunity_Queries {
  private static TA_Opportunity_Queries instance;

  private TA_Opportunity_Queries() {
  }

  public static TA_Opportunity_Queries getInstance() {
    if (TA_Opportunity_Queries.instance == null) {
      TA_Opportunity_Queries.instance = new TA_Opportunity_Queries();
    }
    return TA_Opportunity_Queries.instance;
  }

  public Map<Id, Account> beforeAccountMap { get; private set; }

  public class Service implements TriggerAction.BeforeInsert {
    public void beforeInsert(List<Opportunity> newList) {
      TA_Opportunity_Queries.getInstance().beforeAccountMap = getAccountMapFromOpportunities(
        newList
      );
    }

    private Map<Id, Account> getAccountMapFromOpportunities(
      List<Opportunity> newList
    ) {
      Set<Id> accountIds = new Set<Id>();
      for (Opportunity myOpp : newList) {
        accountIds.add(myOpp.AccountId);
      }
      return new Map<Id, Account>(
        [SELECT Id, Name FROM Account WHERE Id IN :accountIds]
      );
    }
  }
}
``` 
So the `Apex_Class_Name__c` value on the `Trigger_Action__mdt` row should be:
```
TA_Opportunity_Queries.Service
```

![image](https://user-images.githubusercontent.com/18402464/211059957-1659076f-c0e0-44d9-9e7a-f9efb5731719.png)

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/18402464/211060102-3fc3bc1b-962c-4a63-a7dc-898f3b2325af.png">

```java
System.Savepoint sp = Database.setSavepoint();
Account acme = new Account(Name = 'Acme');
insert acme;

Opportunity opp = new Opportunity(
    Name = 'Sample Opportunity',
    CloseDate = Date.today(),
    StageName = 'Prospecting',
    AccountId = acme.Id
);
insert opp;

opp = [SELECT Id, Name FROM Opportunity WHERE Id = :opp.Id];
System.Assert.areEqual('Acme | Sample Opportunity', opp.Name);
Database.rollback(sp);
```

The system is working as intended, so I will close this issue, but I will also update the documentation to make this clearer for future readers.

**Closed by mitchspano** 2023-01-06 17:07 UTC

**Comment by rarpit** [comment] 2023-01-06 20:24
Thank you @mitchspano for quick resolution.
