### ISSUE TITLE
Bypassed MDT Causes Apex Tests to Fail

### ISSUE THREAD

**Issue by ctcforce** [mitchspano/apex-trigger-actions-framework#137] opened 2024-01-30 18:28 UTC
## Expected Behavior
When an `sObject_Trigger_Setting__mdt` or `Trigger_Action__mdt` has `Bypass_Execution__c` == `TRUE`, during execution of apex test class methods, TAF should execute the configured Trigger Action anyways.

## Actual Behavior
Apex test methods that rely on TAF executing a configured trigger action fail when a global bypass is set in the MDT.

## Steps to Reproduce the Problem

1. run a known working apex test class method that relies on the TAF
1. bypass either the corresponding sobject mdt or trigger action mdt
1. run apex test class method again, witness failure

## Specifications

- Version: 0.2.8
- Platform: Salesforce sandbox

**Comment by mitchspano** [comment] 2024-01-30 18:36
There are two solution to this:

1) Do not perform DML to test your trigger logic - see https://github.com/mitchspano/apex-trigger-actions-framework?tab=readme-ov-file#dml-less-trigger-testing

2) Inject the `Trigger_Action__mdt` rows you want into execute into `MetadataTriggerHandler` during test execution:
https://github.com/mitchspano/apex-trigger-actions-framework/blob/main/trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls#L339

Generally speaking - this is not an issue with the framework, but a structural change which is to be made to they way unit tests are to be written in your org.

The system is working as intended, so I am closing this issue.

**Comment by mitchspano** [comment] 2024-02-09 17:07
This can be accomplished without any modifications to the framework by leveraging the fact that the inner `MetadataTriggerHandler.Selector` is `@TestVisible` and `virtual`:

```java
@TestVisible
private virtual inherited sharing class Selector {
  public virtual List<SObject> query(String queryString) {
    return Database.query(queryString);
  }
}
```

So in a test class, you can override this and mutate the query results however you like:

```java
@IsTest
private class SomeTest {

  @IsTest
  private static void fooShouldBar() {
    MetadataTriggerHandler.selector = new SomeTest.FakeSelector();
  
    insert new Account(Name = 'Acme'); // _all_ trigger actions will execute now, regardless of `Bypass_Execution__c` value
  }

  private class FakeSelector extends MetadataTriggerHandler.Selector {
    public override List<SObject> query(String queryString) {
      String queryStringWithoutBypassCheck = queryString.replace('AND Bypass_Execution__c = FALSE', '');
      List<SObject> allTriggerActionsForThisContext = Database.query(queryStringWithoutBypassCheck);
      // mutate further if you like - perhaps setting `Bypass_Permission__c` or `Required_Permission__c` as needed
      return allTriggerActionsForThisContext;
    }
  }
}
```

**Closed** 2024-02-22 18:57 UTC
